# java -jar selenium-server-4.8.0.jar node --config selenium-server-nodes.toml

[node]
detect-drivers = true
grid-url = "http://localhost:4444/"
override-max-sessions = false

[[node.driver-configuration]]
display-name = "MicrosoftEdge 109.0"
max-sessions = 2
stereotype = "{\"browserName\": \"MicrosoftEdge\", \"browserVersion\": \"109.0\", \"platformName\": \"Windows\"}"

[[node.driver-configuration]]
display-name = "Chrome 109.0"
max-sessions = 3
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"109.0\", \"platformName\": \"Windows\"}"

[[node.driver-configuration]]
display-name = "Firefox 109.0"
max-sessions = 2
stereotype = "{\"browserName\": \"firefox\", \"browserVersion\": \"109.0\", \"platformName\": \"Windows\"}"
